### ISSUE TITLE
"ShiftReg" on right hemisphere wont change loop length. Stuck on "2" steps.

### ISSUE THREAD

**Issue by CompositeCone** [mxmxmx/O_C#109]
Hi! on my version of hemisphere suite, specifically in the right hemisphere and using Shift Register, I cant control the loop length by twisting the encoders. It is just stuck on "2" steps. When I try and move the encoder it instantly just snaps back to "2" even with nothing patched in. Not too sure if this is a firmware bug or I am missing something. Video is attached.

https://user-images.githubusercontent.com/77107623/103903610-3b5b3a00-5150-11eb-998f-78b163ad7e88.mp4

**Comment by altitude909** [comment]
Maybe you should take that up with the Hemisphere person

**Comment by CompositeCone** [comment]
my bad!
