### ISSUE TITLE
Teensy: hex file too large

### ISSUE THREAD

**Issue by chriszanf** [mxmxmx/O_C#116]
My device definitely has the power strip cut so it only powers from the rack but I was trying to download the hex file as instructed under 'method A':

>"(note: if the loader app complains about the .hex file being “too large”, try to load this hex first, so the loader can detect the MCU, then re-try with the OC firmware hex"

By the link to the Google drive file is 403 with "We're sorry, but you do not have access to this document. " (Link: https://drive.google.com/uc?export=download&id=0ByUu4ePJDmVnd3U2RFdqYzJfbVE)

Can you make this file available again please so I can test?

**Comment by patrickdowling** [comment]
I don’t remember what file was linked there but you should be able to just use any .hex file (or compile/upload an empty sketch from the IDE).
This seems to be the basic blinky thing and includes .hex for teensy 3.2:  [blink_both.zip](http://pjrc.com/teensy/blink_both.zip) from [pjrc "Getting Started"](https://www.pjrc.com/teensy/loader.html)

**Comment by chriszanf** [comment]
Thanks!
