### ISSUE TITLE
[AC]

### ISSUE THREAD

**Issue by mxmxmx** [mxmxmx/O_C#17]
todo:

- playmodes (fwd, rev, pnd, rnd, S/H, CV address (-> input_map))
- screensaver: come up w/ something less cluttered/meaningful
- merge chord editor into one view. 
- [ideally, add detune to steps. somehow ... which combination of buttons though?]

**Comment by beeva-luisgonzalez** [comment]
For which app are these propossal enhancements?

**Comment by mxmxmx** [comment]
they're for the 'acid curds' / chord sequencer app (APP_CHORDS). it's more like a note-to-self though.
