### ISSUE TITLE
Build guide gone?

### ISSUE THREAD

**Issue by markfrancombe** [mxmxmx/O_C#18]
Has the build guide at http://ornament-and-cri.me/ been removed for some reason? Was wondering about the 100ks and which they are.. Is it something to do with the arrows printed on the PCB?
Also construction tips for the teensie and oled... but can figure that out...

**Comment by mxmxmx** [comment]
hi,
no, it's still there: hardware > build it!

http://ornament-and-cri.me/build-it/

**Comment by markfrancombe** [comment]
OK thanks alot.
you might wanna change the link at the bottom of https://github.com/mxmxmx/O_C
It SAYS its to the build doc but aint! 

great project thx!

Mark

**Comment by mxmxmx** [comment]
the build guide comprises more than just the step-by-step soldering stuff (BOM, troubleshooting, schematic, calibration, firmware update, and so on). so that's on purpose.
