### ISSUE TITLE
Factory reset!

### ISSUE THREAD

**Issue by beeva-luisgonzalez** [mxmxmx/O_C#19]
Hi!

I've been digging in the docs on how to factory reset all the settings for my O_C but can't find a way to do it... is there a way without reflashing the module?

If not, then I guess this is a feature request :)

**Comment by mxmxmx** [comment]
have you seen the reply on MW by pld?  hold down the up and down buttons simultaneously during boot up, that should reset the settings. 

... true though, i don't think it's in the manual

**Comment by beeva-luisgonzalez** [comment]
I just saw this.. thank you anyway for answering my question :)!

Keep up the good work!
