### ISSUE TITLE
Arduino IDE (> 1.6.9) no longer link properly

### ISSUE THREAD

**Issue by jeremybernstein** [mxmxmx/O_C#3]
Arduino made a change to the IDE which restricts automatic compilation of resources in subfolders (arduino/arduino-builder#148) which breaks this project (linkage errors). You may need to explicitly #include the cpp files (ugly) or simply move the files to the top-level or a src/ folder.

**Comment by mxmxmx** [comment]
moving everything (the relevant bits) to src/ seems the easy fix. see here https://github.com/mxmxmx/temps_utile-/issues/3 (thanks again, jeremy)

we'll will do this for the next release, in the meantime ... 1.6.8./1.6.9 work

**Comment by mxmxmx** [comment]
should be fixed here now: 

https://github.com/patrickdowling/O_C/releases/tag/v1.1.2
