### ISSUE TITLE
Case corrections

### ISSUE THREAD

**Issue by conjure86** [mxmxmx/O_C#5]
Trying to compile via Linux, where it's case sensitive:

`/tmp/build472148504ceda71c5262b9ef872b0295.tmp/sketch/drivers/display.h:28:34: fatal error: SH1106_128x64_Driver.h: No such file or directory
 #include "SH1106_128x64_Driver.h"`

Fixed by changing line 28 of display.h to:

`#include "SH1106_128x64_driver.h"`

**Comment by conjure86** [comment]
Also, line 36 of OC_DAC.cpp calls:

` #include <spififo.h>`

should be recased to:

` #include <SPIFIFO.h>`

**Comment by mxmxmx** [comment]
thanks.
will be [fixed](https://github.com/patrickdowling/O_C/commit/fa3d56d61601ce6846283a568dc2ca9e3b920067) in the next release.

**Comment by mxmxmx** [comment]
should be fixed here now: 

https://github.com/patrickdowling/O_C/releases/tag/v1.1.2
