### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by Zek75** [mxmxmx/O_C#57]
Hi,
I tried to make the 1.3.1 firmware update. When I try method A, it keeps saying that the file is too large. With method B, it also says that o_c_rev.ino.hex is too large et the end, and the arduino software tells that "Teensy did not respond to a USB-based request to automatically reboot.
Please press the PROGRAM MODE BUTTON on your Teensy to upload your sketch."
Idf I press the button, nothing happens, the screen freezes. I swichted on the case as the website says. What can I do?

**Comment by altitude909** [comment]
That's a hardware problem. Your teensy is not initializing and teensy loader is seeing it as a 2.0, not 3.2 (which has lees room).  Are you powering via USB or euro power?  If it was put together correctly, USB power should have been cut so its needs to be powered by your rack before plugging in the USB

**Comment by Zek75** [comment]
Hi,
the module is plugged in the usb port, and the led is on. And I also power the euro. So you think the teensy is too old?

**Comment by altitude909** [comment]
it has to be a 3.1 or 3.2.  Are you using the precompiled hex?  This sounds like a hardware problem, not a software one and should go to the forum, not the software bug report

**Comment by Zek75** [comment]
Ok thanks

**Comment by timchurches** [comment]
Please see point 8 of step 3 of method A on the firmware documentation page.

**Comment by Zek75** [comment]
Hi,
I tried this, but it keeps on saying that the file is too large. What can I do?

**Comment by mxmxmx** [comment]
"Teensy did not respond to a USB-based request to automatically reboot" would suggest you're using a cable meant for charging; i'd suggest try with a different cable.

**Comment by Zek75** [comment]
Ha yes thanks!

**Comment by Zek75** [comment]
Thanks a lot!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
