### ISSUE TITLE
O&C 2e Gerbers have no silkscreen values

### ISSUE THREAD

**Issue by conjure86** [mxmxmx/O_C#6]
2e Gerbers have no bottom silkscreen values. What gives?

**Comment by conjure86** [comment]
Bottom silkscreen (GBO) is corrupt, no matter how many times and different ways I try to download it.

**Comment by mxmxmx** [comment]
corrupt or no values? anyhow, it works here. how do you download GBO?

**Comment by conjure86** [comment]
Interesting. Corrupt on my end, from the zip file downloaded direct from Windows 10 x64. I'll jump on my Linux box and try it there. Thanks :)
