### ISSUE TITLE
Reset Automatonnetz by Trigger

### ISSUE THREAD

**Issue by Triscus** [mxmxmx/O_C#77]
Is it possible to reset the Automatonnetz sequence by a trigger input to the first field?

**Comment by mxmxmx** [comment]
hi, i'm not sure ... it looks as if TR3 is doing something along these lines? [(?)](https://github.com/mxmxmx/O_C/blob/master/software/o_c_REV/APP_AUTOMATONNETZ.ino#L378) @timchurches might know more.

**Comment by patrickdowling** [comment]
Yeah, it should reset if TR3 is high when TR1 is clocked.

**Comment by Triscus** [comment]
Thank you for your replies, it works with TR3.
