### ISSUE TITLE
teensy problems

### ISSUE THREAD

**Issue by dork173** [mxmxmx/O_C#80]
Hi, 

I have recently bought an O_C  U_temps and I have a problem with the teensy.

I can upload the code to the teensy but when I connect the teensy to the module it doesn't respond and Windows doesn't recognize it.
i power up the rack and nothing and the same for the usb

Thank you very much,

Kind regards

**Comment by altitude909** [comment]
You should contact whoever you bought it from, this isnt really the place for hardware tech support.
